# Generated by Django 6.0 on 2026-01-04 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_email',
        ),
    ]
