# Generated by Django 6.0 on 2026-01-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_userprofile_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_assets',
            field=models.IntegerField(default=50),
        ),
    ]
