# Generated by Django 6.0 on 2026-01-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_teaminvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
